### ISSUE TITLE
Il y a certain format de date qui ne passe pas !

### ISSUE THREAD

**Issue by pedrokarim** [pawel956/projetKarimAndCo_ConnexionInscription#1]
En essayant d'utiliser le composant j'ai trouvé un petit souci dans la date quand je mets la date naissance suivant `09/02/2000` il me dis format no ok 

voir :
![image](https://user-images.githubusercontent.com/28218643/66824237-30fbc180-ef48-11e9-8b26-e791af383bf5.png)

**Comment by pawel956** [comment]
@AliasPedroKarim [#53](https://github.com/pawel956/projetKarimAndCo_ConnexionInscription/tree/7f64705d6b7481c64412ea0e56f727c720eefb39) le bug vient d'être corrigé, voici le commit qui contient le correctif du bug
